apiVersion: apps/v1
kind: Deployment
metadata:
  name:  fortune
  labels:
    app:  fortune
spec:
  replicas: 10 # Varies between 2/5/10
  selector:
    matchLabels:
      app: fortune
  template:
    metadata:
      labels:
        app:  fortune
    spec:
      containers:
      - image:  alexanderrasmussen/dps-fortune:1
        imagePullPolicy: IfNotPresent 
        name:  fortune
        resources: # Varies
          requests: 
            cpu: "100m" 
            memory: "100M"
          limits:
            cpu: "200m"
            memory: "200M"
        ports:
        - containerPort:  8080
          name:  fortune
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-service
spec:
  selector:
    app: fortune
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer